# Credit: https://github.com/p1x3l101-10/ssh-port-forward
version: '3.8'

services:
  ssh:
    build: 'https://github.com/p1x3l101-10/ssh-port-forward.git#master:build'
    volumes:
      - global:/global
    environment:
      CONFIG: '/global/ports.conf'
